version: '3.9'

services:
  mongo:
    container_name: powerguard-db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/var/lib/mongodb
    networks:
      - powerguard-net

  mongo-express:
    container_name: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:latest
    restart: always
    profiles: [ "dev" ]
    ports:
      - "80:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: null
    networks:
      - powerguard-net

  redis:
    image: redis:latest
    container_name: powerguard-cache
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - powerguard-net

  api:
    container_name: powerguard-api
    image: joaopalazzolli/powerguard
    build:
      context: .
      dockerfile: Dockerfile
    profiles: [ "prod" ]
    ports:
      - "80:8080"
    volumes:
      - .:/usr/src/powerguard
    networks:
      - powerguard-net

volumes:
  mongo-data:
  redis-data:

networks:
  powerguard-net:
    driver: bridge